version: 2.1

commands:
  check_env_var: 
    description: checking environment variables
    steps:
      - run: |
          echo checking environment variables
          echo MY_ENV is $MY_ENV
          echo MY_REGION is $MY_REGION
          echo BRANCH_NAME is $BRANCH_NAME

jobs:
  develop:
    docker:
      - image: cimg/base:stable
    environment:
      MY_ENV: test
      MY_REGION: ap-south-1
      BRANCH_NAME: develop
    steps:
      - checkout
      - run:
          name: "checking environment variables"
          command: check_env_var

workflows:
  serverless:
    jobs:
      - develop
