version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  check_env_var: 
    description: checking environment variables
    steps:
      - run: |
          echo checking environment variables
          echo MY_ENV is $MY_ENV
          echo MY_REGION is $MY_REGION
          echo BRANCH_NAME is $BRANCH_NAME
  setup_serverless:
    description: setup serverless
    steps: 
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm ci
      - run: 
          name: install serverless framework
          command: npm install -g serverless
      - run: 
          name: authenticate serverless
          command: sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - run: 
          name: install serverless plugins 
          command: sls plugin install --name serverless-python-requirements
  build_pkg: 
    description: build serverless package
    steps: 
      - run: 
          name: build lambda package
          command: sls package --package lambda_pkg --stage=$MY_ENV
      - persist_to_workspace: 

  deploy_pkg:
    description: deploy lambda package
    steps: 
      - run: sls deploy ./lambda_pkg --stage=$MY_ENV

executors:
  base-img:
    docker: cimg/base:stable
    working_directory: /tmp

jobs:
  setup: 
    executor: base-image
    steps: 
      - checkout 
      - setup_serverless    
  develop:
    executor: base-image
    environment:
      MY_ENV: test
      MY_REGION: ap-south-1
      BRANCH_NAME: develop
    steps: 
      - check_env_var
      - build_pkg
      - deploy_pkg
  master: 
    executor: base-image
    environment:
      MY_ENV: prod
      MY_REGION: us-west-2
      BRANCH_NAME: master
    steps: 
      - check_env_var
      - build_pkg
      - deploy_pkg 
  feature: 
    executor: base-image
    environment: 
      MY_ENV: test
      MY_REGION: ap-south-1
      BRANCH_NAME: develop
    steps: 
      - check_env_var
      - build_pkg
      - run: 
          name: test lcoally by invoking lambda function
          command: sls invoke local -f emailer -d "{\"emailId\": \"mohiitlakshya@gmail.com\"}\"

workflows:
  serverless:
    jobs:
      - develop:
          context: aws
          filters:
            branches:
              only: develop
          requires: setup 
      - master: 
          context: aws
          filters:
            branches:
              only: master
          requires: setup
      - feature: 
          context: aws
          filters:
            branches:
              ignores:
                - develop
                - master
          requires: setup

