name: deploy to aws

on: workflow_dispatch

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v3
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: $${{ matrix.node-version }}
      run: npm ci
    - name: serverless install plugin and deploy
      uses: serverless/github-actions@v3
      env:
        MY_ENV: test
        MY_REGION: ap-south-1
        BRANCH_NAME: develop
        AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "$MY_ENV"
        echo MY_REGION is "$MY_REGION"
        echo BRANCH_NAME is "$BRANCH_NAME"
        serverless deploy --stage=test
    
     
