name: deploy to aws

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup environment variables
      run: |
        echo "MY_ENV=test" >> $GITHUB_ENV
        echo "MY_REGION=ap-south-1" >> $GITHUB_ENV
        echo "BRANCH_NAME=develop" >> $GITHUB_ENV
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ env.MY_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: npm ci
    - name: install serverless framework
      run: npm install -g serverless
    - name: serverless authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: install plugins
      run: sls plugin install --name serverless-python-requirements
    - name: build and deploy
      run: sls deploy --verbose
     
